from __future__ import annotations

from .colors import Palette


def render_kitty(p: Palette) -> str:
    lines = [
        "# Generated by pywalnium",
        f"foreground {p.foreground}",
        f"background {p.background}",
        f"cursor {p.cursor}",
    ]
    lines.extend(f"color{i} {value}" for i, value in enumerate(p.colors))
    return "\n".join(lines) + "\n"


def render_alacritty(p: Palette) -> str:
    normal = p.colors[:8]
    bright = p.colors[8:16]
    names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    return (
        "# Generated by pywalnium\n"
        "[colors.primary]\n"
        f'background = "{p.background}"\n'
        f'foreground = "{p.foreground}"\n\n'
        "[colors.normal]\n"
        + "\n".join(f'{name} = "{color}"' for name, color in zip(names, normal, strict=True))
        + "\n\n[colors.bright]\n"
        + "\n".join(f'{name} = "{color}"' for name, color in zip(names, bright, strict=True))
        + "\n"
    )


def render_rofi(p: Palette) -> str:
    return (
        "/* Generated by pywalnium */\n"
        "* {\n"
        f"  background: {p.background};\n"
        f"  foreground: {p.foreground};\n"
        f"  accent: {p.colors[4]};\n"
        "}\n"
    )


def render_hyprland(p: Palette) -> str:
    lines = ["# Generated by pywalnium"]
    lines.extend(f"$color{i} = rgb({c[1:]})" for i, c in enumerate(p.colors))
    lines.append(f"$background = rgb({p.background[1:]})")
    lines.append(f"$foreground = rgb({p.foreground[1:]})")
    return "\n".join(lines) + "\n"


def render_waybar(p: Palette) -> str:
    lines = [
        "/* Generated by pywalnium */",
        ":root {",
        f"  --background: {p.background};",
        f"  --foreground: {p.foreground};",
    ]
    lines.extend(f"  --color{i}: {c};" for i, c in enumerate(p.colors))
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_dunst(p: Palette) -> str:
    return (
        "# Generated by pywalnium\n"
        "[global]\n"
        f"    frame_color = \"{p.colors[4]}\"\n"
        f"    separator_color = \"{p.colors[8]}\"\n"
        "\n[urgency_low]\n"
        f"    background = \"{p.background}\"\n"
        f"    foreground = \"{p.foreground}\"\n"
    )
